apiVersion: v1
kind: Service
metadata:
  name: tor
  namespace: default
  labels:
    app: tor
spec:
  selector:
    app: tor
  ports:
    - name: http
      port: 9050
      targetPort: 9050
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tor
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tor
    spec:
      serviceAccountName: tor
      containers:
        - name: tor
          image: tufin/tor
          imagePullPolicy: Always
          ports:
            - containerPort: 9050
